### ISSUE TITLE
DIR_REVERSE and dir_t should be documented

### ISSUE THREAD

**Issue by utahwithak** [freeserf/freeserf#169]
in Map.h there is the macro:

    #define DIR_REVERSE(dir)  ((dir_t)(((dir) + 3) % 6))

this is used with the enum (explicit values added):

    DIR_NONE = -1

    DIR_RIGHT = 0
    DIR_DOWN_RIGHT = 1,
    DIR_DOWN = 2,
    DIR_LEFT = 3,
    DIR_UP_LEFT = 4,
    DIR_UP = 5,

    DIR_UP_RIGHT = 6,
    DIR_DOWN_LEFT = 7

If you call DIR_REVERSE(DIR_UP_RIGHT) you will get DIR_LEFT ((6+3) % 6) = 3
and if you call DIR_REVERSE(DIR_DOWN_LEFT) you will get DIR_UP_LEFT ((7+3) %6) = 4

A correct version would look something like this:
Right = 0
UpRight = 1
Up = 2
UpLeft = 3
Left = 4
DownLeft = 5
Down = 6
DownRight = 7

Reverse would be  (dir + 4) % 8

I understand this would probably break saving and loading but thought you should probably know.

**Comment by jonls** [comment]
Yes, you are correct that `DIR_REVERSE` does not work for `DIR_UP_RIGHT` and `DIR_DOWN_LEFT`. In some sense, these two directions are non-standard because they don't correspond to an actual edge between two points on the map. Looking through the source code, it seems that they are currently only used in the map construction. `DIR_UP_RIGHT` is actually also used as a kind of error flag in `game.c` but that should probably just be changed to `DIR_NONE`.

I think `DIR_UP_RIGHT` and `DIR_DOWN_LEFT` could actually be removed completely. If not, I agree that it should be documented that `DIR_REVERSE` does not work for these directions.

**Comment by utahwithak** [comment]
Just trying to understand, what do you mean they don't correspond to an actual edge between two points? if the map is something like:
          A ___ B
          / \       /
         /    \   /
   C /____\/ D

aren't there up right's DB and CA or down lefts in the opposite direction. What am I missing?

**Comment by jonls** [comment]
I was going to direct you to the comment at the top of `map.c` but I realize now that it does not fully explain the directions. Here is diagram showing the point D and all the neighboring points.

       A _______B____ X
        /\    /\    /
       /  \  /  \  /
    C /____\/_D__\/ E
      \    /\    /
       \  /  \  /
        \/_F__\/ G

The direction from D -> E is `DIR_RIGHT`, D -> G is `DIR_DOWN_RIGHT`, D -> F is `DIR_DOWN`, D -> C is `DIR_LEFT`, D -> A is `DIR_UP_LEFT` and D -> B is `DIR_UP`. The direction `DIR_UP_RIGHT` is D -> X but there is no edge on the map connecting these points.

**Comment by utahwithak** [comment]
That helps immensely and clarifies what you were meaning. Thanks for putting that together. I might suggest adding that to maps.c but it's probably overkill.

**Comment by jonls** [comment]
Great, I'm glad it helped. I think the existing documentation in `map.c` could be extended to include this. I'll reopen this bug so I can add that later.
